service: snapstore-service

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  profile: default

custom:
  webpackIncludeModules: true

plugins:
  - serverless-webpack  

CreateUser:
  handler: user.CreateUser
  events:
    - http:
        path: user
        method: post
        cors: true
        integration: lambda
GetUser:
  handler: user.GetUser
  events:
    - http:
        path: user/{user_id}
        method: get
        cors: true         
        integration: lambda         
FindUserByEmail:
  handler: user.FindUserByEmail
  events:
    - http:
        path: phone/{phoneNumber}
        method: get
        cors: true         
        integration: lambda            
UpdateUser:
  handler: users.UpdateUser
  events:
    - http:
        path: user/{user_id}
        method: put
        cors: true         
        integration: lambda                