service: snapstore-service

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  profile: default

custom:
  webpackIncludeModules: true

plugins:
  - serverless-webpack  

functions:
  createUser:
    handler: user.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
          integration: lambda
  getUser:
    handler: user.getUser
    events:
      - http:
          path: user/{userId}
          method: get
          cors: true         
          integration: lambda         
  findUserByEmail:
    handler: user.findUserByEmail
    events:
      - http:
          path: email/{email}
          method: get
          cors: true         
          integration: lambda            
  updateUser:
    handler: users.updateUser
    events:
      - http:
          path: user/{userId}
          method: put
          cors: true         
          integration: lambda                